---

- name: Reboot all hosts before deploy Kube
  hosts: ocne_op ocne_kube_control ocne_kube_worker
  become: yes
  become_user: root
  gather_facts: false

  tasks:
  - name: Reboot all hosts
    shell: |
           sudo reboot 

  - name: Wait for host to be available
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      timeout: 600
