---

- name: Reboot all hosts before deploy Kube
  hosts: ocne_op ocne_kube_control ocne_kube_worker
  become: yes
  become_user: root
  gather_facts: false

  tasks:
  - name: Reboot all hosts
    reboot: